"""Voice asset text selected from docs/PLAN.md."""

VOICE_ASSETS = [
    {
        "track": 1,
        "filename": "0001.mp3",
        "trigger": "你好",
        "state": "GREETING",
        "text": "你好，有什么可以帮您",
        "tokens": 36,
        "max_new_tokens": 64,
        "instruction": "温柔、轻快、像桌面陪伴小花一样亲近自然。",
    },
    {
        "track": 2,
        "filename": "0002.mp3",
        "trigger": "介绍自己",
        "state": "SELF_INTRO",
        "text": "我是一朵会追光的闲聊花，可以陪你说说话",
        "tokens": 60,
        "max_new_tokens": 76,
        "instruction": "明亮、可爱、带一点自豪感，但不要夸张。",
    },
    {
        "track": 3,
        "filename": "0003.mp3",
        "trigger": "我有点累",
        "state": "TIRED_RESPONSE",
        "text": "那就休息一下吧，喝口水，看看远处",
        "tokens": 52,
        "max_new_tokens": 76,
        "instruction": "放慢语速，语气安慰、柔和，像提醒朋友休息。",
    },
    {
        "track": 4,
        "filename": "0004.mp3",
        "trigger": "今天开心",
        "state": "HAPPY_RESPONSE",
        "text": "太好啦，希望这份开心一直陪着你",
        "tokens": 48,
        "max_new_tokens": 88,
        "instruction": "开心、轻盈、真诚，结尾保持温暖。",
    },
    {
        "track": 5,
        "filename": "0005.mp3",
        "trigger": "我要走了",
        "state": "GOODBYE",
        "text": "好的，待会儿见，我会继续面朝阳光",
        "tokens": 56,
        "max_new_tokens": 96,
        "instruction": "平静、依依不舍但不过度，像温柔告别。",
    },
]
